deployment:
  tasks:
    - export DEPLOYPATH=/home/tronsdev/public_html/rcm-tool
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R build/* $DEPLOYPATH